routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use App\Libs\Binance;
use App\Models\Currency;
use App\Http\Controllers\Auth\ForgotPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/', function () { return view('landing'); });
Route::get('/', 'DashboardController@landing');
Route::get('/about-us', function () {
return view('land.about-us');
});
Route::get('/user-agreement', function () {
return view('tnc');
});
Route::get('/contact-us', function () {
return view('land.contact');
});
Route::get('/privacy-policy', function () {
return view('prvpol');
});
Route::get('/career', function () {
return view('land.career');
});
Route::get('/products', function () {
     $currency           = Currency::where('active',1)->orderBy('name')->get();
        $coin               = [];
        foreach ($currency as $rows) {
            $binance                                = NEW Binance;
            $send['url']                            = '/ticker/24hr';
            $body['symbol']                         = $rows->code;
            $send['body']                           = $body; 
            $post                                   = $binance->callApi($send);
            if($post) {
                $list['id']                         = $rows->id;
                $list['image']                      = $rows->image;
                $list['code']                       = $rows->code;
                $list['name']                       = $rows->name;
                $list['price']                      = $post->lastPrice;
                $list['change']                     = $post->priceChangePercent;
                $list['highPrice']                  = $post->highPrice;
                $list['lowPrice']                   = $post->lowPrice;
                $list['marketPrice']                = $post->quoteVolume;
                $coin[]                             = $list;
            }   
        }
        $row                                        = json_decode(json_encode($coin), FALSE);
return view('land.products')->with(compact('row'));
});
Route::get('/partnership', function () {
return view('land.partnership');
});
Route::get('/news', function () {
return view('land.news');
});
Route::get('/page/{slug}', 'DashboardController@page');
Route::get('/calculate', 'DashboardController@calculate');



Route::resource('login', 'LoginController');
Route::get('/login', function () {
    return view('login');
})->name('login');
Route::resource('register', 'RegisterController');
Route::resource('cron', 'CronController');
Route::get('bscscan', 'CronController@bscscan');
Route::get('markets', 'CronController@create');

Route::post('cfaspay', 'TransactionController@cfaspay');
Route::post('faspay', 'TransactionController@faspay');
// Route::post('faspay_notify', 'TransactionController@faspay_notify');
// Route::post('faspay_notify', 'TransactionController@faspay_notify');
Route::get('/faspay/thankyou', 'TransactionController@faspay_callback');

Route::get('forget-password', [ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');
Route::post('forget-password', [ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post'); 
Route::get('reset-password/{token}', [ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
Route::post('reset-password', [ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'DashboardController@index');
    Route::get('/market', 'MarketController@index');
    Route::resource('balance', 'BalanceController');
    Route::resource('buy', 'BuyController');
    Route::resource('deposit', 'DepositController');

    Route::post('withdraw/info', 'WithdrawController@postInfo');
    Route::get('bank', 'WithdrawController@bank');
    Route::post('add_bank', 'WithdrawController@add_bank');
    Route::post('edit_bank/{id}', 'WithdrawController@edit_bank');
    Route::post('del_bank/{id}', 'WithdrawController@del_bank');
    Route::get('withdraw/info', 'WithdrawController@getInfo');
    Route::post('/withdraw/sendme_notify', 'WithdrawController@sendme_notify');
    Route::get('/testemail', 'WithdrawController@testemail');
    Route::resource('withdraw', 'WithdrawController');

    Route::post('transaction/confirm', 'TransactionController@confirm');
    Route::post('transaction/wconfirm', 'TransactionController@wconfirm');
    Route::get('transaction/depo_confirm/{id}', 'TransactionController@adm_confirm');
    Route::get('transaction/wd_confirm/{id}', 'TransactionController@wadm_confirm');
    Route::post('transaction/dp_update', 'TransactionController@trx_confirm');
    Route::post('transaction/dp_reject', 'TransactionController@trx_reject');
    Route::post('transaction/wd_update', 'TransactionController@wtrx_confirm');
    Route::post('transaction/wd_reject', 'TransactionController@wtrx_reject');
    Route::get('transaction/adm', 'TransactionController@index_adm');
    Route::resource('transaction', 'TransactionController');
    Route::resource('account', 'AccountController');
    Route::resource('tokocrypto', 'TokocryptoController');

    Route::get('currency/activate/{id}', 'CurrencyController@activate');
    Route::resource('currency', 'CurrencyController');

    Route::get('verification/list', 'VerificationController@list');
    Route::get('verification/bank', 'VerificationController@bank');
    Route::post('verification/bank', 'VerificationController@storeBank');
    Route::get('verification/file', 'VerificationController@file');
    Route::post('verification/file', 'VerificationController@storeFile');
    Route::get('verification/done', 'VerificationController@done');
    Route::resource('verification', 'VerificationController');

    Route::post('user/verification', 'UserController@approve');
    Route::get('user/verification/{id}', 'UserController@verification');
    Route::get('user/assets/{id}', 'UserController@assets');
    Route::resource('user', 'UserController');

    Route::resource('admin', 'AdminController');
    Route::resource('agentrole', 'AgentRoleController');
    Route::get('agentrequest', 'AgentController@reqlist');
    Route::post('agent/req', 'AgentController@req');
    Route::post('agent/approve', 'AgentController@approve');
    Route::post('agent/reject', 'AgentController@reject');
    Route::get('agent/done', 'AgentController@done');
    Route::get('agent/landing', 'AgentController@landing');
    Route::resource('agent', 'AgentController');


    Route::group(['prefix' => 'webadmin'], function () {
        Route::get('media', 'WebadminController@listMedia')->name('webadmin.media');
        Route::post('media/upload', 'WebadminController@uploadMedia')->name('webadmin.uploadmedia');

        Route::get('pages', 'WebadminController@listPages')->name('webadmin.pages');
        Route::post('pages/add', 'WebadminController@addPages')->name('webadmin.addpages');
        Route::get('pages/edit/{id}', 'WebadminController@detailPages');
        Route::post('pages/edit', 'WebadminController@editPages')->name('webadmin.editpages');
        Route::get('pages/noactive/{id}', 'WebadminController@noactivePages');
        Route::get('pages/active/{id}', 'WebadminController@activePages');

        Route::get('customvar', 'WebadminController@customvar')->name('webadmin.customvar');
        Route::post('customvar/add', 'WebadminController@addCustomvar')->name('webadmin.addcustomvar');
        Route::get('customvar/edit/{id}', 'WebadminController@detailCustomvar');
        Route::post('customvar/edit', 'WebadminController@editCustomvar')->name('webadmin.editcustomvar');
    });

    Route::post('datalog/search', 'DatalogController@postSearch');
    Route::get('datalog/search', 'DatalogController@getSearch');
    Route::resource('datalog', 'DatalogController');

    Route::post('idcash/activate', 'AccountController@idcash');
    Route::post('idcash/connect', 'AccountController@idcashConnect');
    Route::get('idcash/done', 'AccountController@idcashDone');

    Route::resource('password', 'PasswordController');
    Route::get('/logout', function () { Auth::logout(); return redirect('/'); });
});

resources/views/admin/create.blade.php
@extends('index')
@section('content')
<header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
    <div class="container-xl px-4">
        <div class="page-header-content">
            <div class="row align-items-center justify-content-between pt-3">
                <div class="col-auto mb-3">
                    <h1 class="page-header-title">
                        <div class="page-header-icon"><i data-feather="user"></i></div>
                        Tambah Admin
                    </h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main page content-->
<div class="container-xl px-4 mt-4">
    <div class="row">
        <div class="col-xl-12">
            <form class="card mb-4" method="POST" action="{{url('admin')}}">
                @csrf
                <div class="card-header">Tambah Admin</div>
                <div class="card-body">
                    @if(session('error'))
                    <div class="alert alert-danger alert-icon" role="alert">
                        <div class="alert-icon-aside">
                            <i data-feather="alert-triangle"></i>
                        </div>
                        <div class="alert-icon-content">
                            {{ session('error') }}
                        </div>
                    </div>
                    @endif

                    @if(session('success'))
                    <div class="alert alert-success alert-icon" role="alert">
                        <div class="alert-icon-aside">
                            <i data-feather="check-circle"></i>
                        </div>
                        <div class="alert-icon-content">
                            {{ session('success') }}
                        </div>
                    </div>
                    @endif
                    
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label class="small mb-1">Nama</label>
                            <input class="form-control form-control-solid" type="text" placeholder="Masukan nama admin" name="name" value="{{ old('name') }}" required />
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="small mb-1">Email</label>
                            <input class="form-control form-control-solid" type="text" placeholder="Masukan email admin" name="email" value="{{ old('email') }}" required />
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="small mb-1">No. Handphone</label>
                            <input class="form-control form-control-solid" type="text" placeholder="Masukan no. handphone admin" name="phone" value="{{ old('phone') }}" required />
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="small mb-1">Password</label>
                            <input class="form-control form-control-solid" type="password" name="password" required />
                        </div>
                    </div>
                        
                </div>

                <div class="card-footer">
                    <a class="btn btn-light mr-3" href="{{url('admin')}}">Batal</a>
                    <button class="btn btn-primary" type="submit">Proses</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
                

resources/views/admin/edit.blade.php
@extends('index')
@section('content')
<header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
    <div class="container-xl px-4">
        <div class="page-header-content">
            <div class="row align-items-center justify-content-between pt-3">
                <div class="col-auto mb-3">
                    <h1 class="page-header-title">
                        <div class="page-header-icon"><i data-feather="user"></i></div>
                        Edit Admin
                    </h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main page content-->
<div class="container-xl px-4 mt-4">
    <div class="row">
        <div class="col-xl-12">
            <form class="card mb-4" method="POST" action="{{url('admin')}}/{{ $row->id }}">
                @csrf
                <input name="_method" type="hidden" value="PUT">
                <div class="card-header">Edit Admin</div>
                <div class="card-body">
                    @if(session('error'))
                    <div class="alert alert-danger alert-icon" role="alert">
                        <div class="alert-icon-aside">
                            <i data-feather="alert-triangle"></i>
                        </div>
                        <div class="alert-icon-content">
                            {{ session('error') }}
                        </div>
                    </div>
                    @endif

                    @if(session('success'))
                    <div class="alert alert-success alert-icon" role="alert">
                        <div class="alert-icon-aside">
                            <i data-feather="check-circle"></i>
                        </div>
                        <div class="alert-icon-content">
                            {{ session('success') }}
                        </div>
                    </div>
                    @endif
                    
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label class="small mb-1">Nama</label>
                            <input class="form-control form-control-solid" type="text" placeholder="Masukan nama user" name="name" value="{{ $row->name }}" required />
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="small mb-1">Email</label>
                            <input class="form-control form-control-solid" type="text" placeholder="Masukan email user" name="email" value="{{ $row->email }}" required />
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="small mb-1">No. Handphone</label>
                            <input class="form-control form-control-solid" type="text" placeholder="Masukan no. handphone user" name="phone" value="{{ $row->phone }}" required />
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="small mb-1">Ganti Password</label>
                            <input class="form-control form-control-solid" type="password" placeholder="Kosongkan jika tidak ingin mengganti password" name="password" />
                        </div>
                    </div>
                        
                </div>

                <div class="card-footer">
                    <a class="btn btn-light mr-3" href="{{url('admin')}}">Batal</a>
                    <button class="btn btn-primary" type="submit">Proses</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
                

resources/views/admin/index.blade.php
@extends('index')
@section('style')
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap4.min.css" />
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap.min.css" />
@endsection
@section('js')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/responsive.bootstrap.min.js"></script>
<script>
    $(document).ready(function() {
    $('#table').DataTable({
        responsive: true,
        "dom": 't'
    });
} );
</script>
@endsection
@section('content')
<header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
    <div class="container-xl px-4">
        <div class="page-header-content">
            <div class="row align-items-center justify-content-between pt-3">
                <div class="col-auto mb-3">
                    <h1 class="page-header-title">
                        <div class="page-header-icon"><i data-feather="user"></i></div>
                        Akses Admin
                    </h1>
                </div>
                <div class="col-12 col-xl-auto mb-3"><a href="{{url('admin/create')}}" class="btn btn-sm btn-light"><i data-feather="plus"></i>&nbsp; Tambah Admin</a></div>
            </div>
        </div>
    </div>
</header>
<!-- Main page content-->
<div class="container-xl px-4 mt-4">
    <div class="card">
        <!-- <div class="card-header">Example Card</div> -->
        <div class="card-body">
            <table class="table" id="table">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Phone</th>
                        <th scope="col" style="width:130px;"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($row as $rows)
                    <tr>
                        <td class="avatar avatar-lg align-middle mt-2 mb-2"><img src="{{ $rows->getAvatar() }}" class="avatar-img"></td>
                        <td class="align-middle">{{ $rows->name }}</td>
                        <td class="align-middle">{{ $rows->email }}</td>
                        <td class="align-middle">{{ $rows->phone }}</td>
                        <td class="text-right align-middle">
                        <div class="btn-group">
                            <a href="{{url('admin')}}/{{ $rows->id }}/edit" class="btn btn-light btn-sm"><i data-feather="edit"></i></a>
                            <button class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#alertModal{{ $rows->id }}" data-id="{{ $rows->id }}" data-name="{{ $rows->name }}"><i data-feather="trash"></i></button>
                        </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@foreach($row as $rowss)
<form method="POST" action="{{route('admin.destroy', $rowss->id)}}" class="modal fade" id="alertModal{{ $rowss->id }}" tabindex="-1" role="dialog" aria-labelledby="alertModalLabel" aria-hidden="true">
        @csrf
        <input name="_method" type="hidden" value="DELETE">
        <input name="id" type="hidden" id="user-id">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Konfirmasi!</h5>
                <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                Yakin akan menonaktifkan admin {{$rowss->id}}<span id="user-name"></span> ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">Tidak</button>
                <button type="submit" class="btn btn-danger">Ya</button>
            </div>
            </div>
        </div>
    </form>
@endforeach
@endsection
@push('script')
<script type="text/javascript">
	$('#alertModal').on('show.bs.modal', function(event) {
        var modal 	= $(this);
        var button 	= $(event.relatedTarget);
		$('#user-id').val(button.data('id'));
        $('#user-name').html(button.data('name'));
    });
</script>
@endpush
                